### PR TITLE
Entity properties

### PR DESCRIPTION
**Pull request by Damngoblin**
This PR includes class: Properties, Building(abstract), House(extends Building), Hotel (extends Building). TestCases: PropertiesTest

### CODE REVIEW

**Review by adamjvalentini — COMMENTED** [review]
Looks good to me! The inheritance makes the code more organized

**Review by adamjvalentini — APPROVED** [review]
The name addition looks good

**Review by adamjvalentini — APPROVED** [review]

**Review by adamjvalentini — APPROVED** [review]

**Review by raelws — APPROVED** [review]

**Review by pujiacheng — APPROVED** [review]

**Review by Eileen1003 — APPROVED** [review]

**Review by Davidh1021 — APPROVED** [review]
Just a simple change suggestion on liune 19, where the variable name starts with a capital letter. If thats negligible, then don't mind about this.

**Comment by Damngoblin** [comment]
> Just a simple change suggestion on line 19, where the variable name starts with a capital letter. If thats negligible, then don't mind about this.

**Pull request merged**
